// Builds supabase/seed.sql from game configs (SPEC §2, §7.1). Pure: returns a string.
// Idempotent: every insert uses deterministic natural keys and `on conflict do nothing`.
import type { GameDef } from '../core/types';

export interface PlanSeed { key: string; name: string; description: string; entitlements: Record<string, number | null>; }

export const PLANS: PlanSeed[] = [
  { key: 'free', name: 'Free', description: 'Game 1 and your statue, free forever.', entitlements: { statue_rerolls: 1 } },
  { key: 'pro', name: 'Pro', description: 'Extra statue re-rolls and Pro perks.', entitlements: { statue_rerolls: 5 } },
];

/** SQL string literal. */
export function sqlText(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function sqlJson(value: unknown): string {
  return `${sqlText(JSON.stringify(value))}::jsonb`;
}

function sqlValue(value: unknown): string {
  if (value === null || value === undefined) return 'null';
  if (typeof value === 'number') return Number.isFinite(value) ? String(value) : 'null';
  if (typeof value === 'boolean') return value ? 'true' : 'false';
  if (typeof value === 'string') return sqlText(value);
  return sqlJson(value);
}

const gameIdSql = (slug: string) => `(select id from public.games where slug = ${sqlText(slug)})`;

export interface GameSeed { game: GameDef; type: 'free' | 'paid' | 'earning'; status: string; }

export function buildSeedSql(games: GameSeed[], plans: PlanSeed[] = PLANS): string {
  const out: string[] = [
    '-- GENERATED by scripts/gen-seed.ts from src/games. Do not edit by hand.',
    '-- Idempotent: safe to run more than once.',
    'begin;',
    '',
    '-- Plans and entitlements',
  ];
  for (const p of plans) {
    out.push(`insert into public.plans (key, name, description) values (${sqlText(p.key)}, ${sqlText(p.name)}, ${sqlText(p.description)}) on conflict (key) do nothing;`);
    for (const [feature, limit] of Object.entries(p.entitlements)) {
      out.push(`insert into public.entitlements (plan_id, feature_key, limit_value) values ((select id from public.plans where key = ${sqlText(p.key)}), ${sqlText(feature)}, ${sqlValue(limit)}) on conflict (plan_id, feature_key) do nothing;`);
    }
  }

  for (const { game, type, status } of games) {
    const { quests, achievements, ...rest } = game;
    out.push('', `-- Game ${game.id}: ${game.title}`);
    out.push(`insert into public.games (slug, title, type, status, config) values (${sqlText(game.id)}, ${sqlText(game.title)}, ${sqlText(type)}, ${sqlText(status)}, ${sqlJson(rest)}) on conflict (slug) do nothing;`);
    quests.forEach((q, i) => {
      const cols = ['game_id', 'key', 'pillar', 'title', 'founding', 'schedule', '"window"', 'proof', 'xp', 'unlock', 'sort_order'];
      const vals = [gameIdSql(game.id), sqlText(q.id), sqlText(q.pillar), sqlText(q.title), sqlValue(q.founding), sqlJson(q.schedule), sqlJson(q.window), sqlJson(q.proof), String(q.xp), sqlJson(q.unlock), String(i + 1)];
      out.push(`insert into public.quests (${cols.join(', ')}) values (${vals.join(', ')}) on conflict (game_id, key) do nothing;`);
    });
    for (const a of achievements) {
      const vals = [sqlText(a.id), gameIdSql(game.id), sqlText(a.name), sqlText(a.scope), sqlValue(a.hidden), sqlJson(a.rule), sqlValue(a.decoration ?? null)];
      out.push(`insert into public.achievements (key, game_id, name, scope, hidden, rule, decoration) values (${vals.join(', ')}) on conflict (key) do nothing;`);
    }
  }
  out.push('', 'commit;', '');
  return out.join('\n');
}
